# Generated by Django 4.2.5 on 2023-09-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergingDJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=100)),
                ('music_genre', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
