# Generated by Django 4.2.5 on 2023-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergingdj',
            name='soundcloud_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
