# Generated by Django 4.2.5 on 2023-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_emergingdj_soundcloud_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergingdj',
            name='image',
            field=models.ImageField(blank=True, upload_to='dj_images/'),
        ),
    ]
